### ISSUE TITLE
Controllo nuova prenotazione

### ISSUE THREAD

**Issue by danesinoo** [Sdraiati/Grigo-Verde#23]
Bisogna controllare che la nuova prenotazione funzioni al path `dashboard/nuova-prenotazione`

**Comment by simocare** [comment]
@danesinoo 
- se due utenti prenotano la stessa aula nello stesso orario non viene restituito un errore;
- se viene fatta una prenotazione su uno spazio es. 11-12 e provo a prenotare dalle 11 alle 11:30 mi lascia;
- può prenotare anche l'admin (non so se lo vogliamo lasciare).

**Comment by danesinoo** [comment]
@simocare 
dovrei aver corretto i primi due punti, mentre direi che vogliamo che l'amministratore abbia la possibilità di prenotare

**Comment by simocare** [comment]
@danesinoo 
![image](https://github.com/user-attachments/assets/23756a5e-0563-4c76-baac-87113c8a920a)
Qui non capisco perché mi sta dicendo che non è aperto in quell'orario
