### ISSUE TITLE
Modifica Utente

### ISSUE THREAD

**Issue by danesinoo** [Sdraiati/Grigo-Verde#34]
Molto simile a Crea Utente, deve permettere di modificare le informazioni della creazione dell'utente, si noti che la password è una di queste.

**Comment by simocare** [comment]
@danesinoo seguendo quello che avviene nella maggior parte dei siti di questo tipo, la password viene assegnata dall'amministatore e poi è solo l'utente che può modificarsela.

**Comment by danesinoo** [comment]
@simocare prendendo SIAGAS, il portale di Tullio come esempio questo non è vero: l'amministratore ha modo di modificare la password. Lo so perché me la sono dimenticata e Tullio mi ha detto sia il nome utente e mi ha resettato la password

**Comment by simocare** [comment]
Ok mi sembra sensato.

**Comment by simocare** [comment]
Togliere la tabella se non ci sono prenotazioni e mettere a lato il form come nella dashboard
