### ISSUE TITLE
Gerarchia delle pagina

### ISSUE THREAD

**Issue by danesinoo** [Sdraiati/Grigo-Verde#38]
1. Stilare un albero delle pagine a partire dalla mappa del sito
2. Dall'albero si definiscono i breadcrumb di ciascuna pagina
3. Si definisce la navbar (uguale per ogni pagina, all'interno di `Page`)
4. Controllare i breadcrumb di ciascuna pagina

**Comment by simocare** [comment]
> 1. Stilare un albero delle pagine a partire dalla mappa del sito
> 2. Dall'albero si definiscono i breadcrumb di ciascuna pagina
> 3. Si definisce la navbar di ciascuna pagina
> 4. Controllare i breadcrumb di ciascuna pagina
> 5. Controllare le navbar di ciascuna pagina

@danesinoo  La navbar deve essere la stessa in tutte le pagine, per non disorientare l'utente

**Comment by danesinoo** [comment]
Ottimo, allora possiamo inserire la navbar direttamente con la classe `Page` rendendo il metodo per fare la navbar privato

**Comment by danesinoo** [comment]
Ho individuato le seguenti gerarchie:
- Utente non autenticato
<img width="258" alt="Screenshot 2024-08-09 at 11 46 36" src="https://github.com/user-attachments/assets/e8ac7f84-2a4a-4396-a307-cea126f06a1f">
- Docente
<img width="360" alt="Screenshot 2024-08-09 at 11 46 47" src="https://github.com/user-attachments/assets/a756e6d8-bfdb-4ace-9b2b-7e95e415ac36">
- Amministratore
<img width="484" alt="Screenshot 2024-08-09 at 11 46 51" src="https://github.com/user-attachments/assets/d40efdd9-344c-4cce-ae10-2262b345c6aa">

Da cui derivano le seguenti navs:
- Utente non autenticato: 
  - Home
  - Spazi
  - About Us
- Docente
  - Dashboard 
  - Spazi 
  - About Us
- Amministratore
  - Dashboard 
  - Spazi 
  - Utenti 
  - About Us
