### ISSUE TITLE
Pagina delle prenotazioni

### ISSUE THREAD

**Issue by danesinoo** [Sdraiati/Grigo-Verde#47]
Sembra essere necessario realizzare una pagina di tutte le prenotazioni generica: indipendente dall'utente e dallo spazio. Questo è necessario perché un utente generico può accedere al dettaglio di una prenotazione, ma non ha una dashboard. Quindi
1. o l'utente non è in grado di vedere nessuna prenotazione
2. oppure bisogna realizzare un percorso delle pagine attraverso il quale l'utente può accedere al dettaglio di una prenotazione

**Comment by simocare** [comment]
Se la tabella è vuota deve riportare una scritta: Non hai effettuato prenotazioni, al posto della tabella.
