### ISSUE TITLE
endpoint per l'autenticazione

### ISSUE THREAD

**Issue by danesinoo** [Sdraiati/Grigo-Verde#5]
Ovvero, Simone sta creando la pagina per effettuare l'autenticazione, questa pagina, invia dei dati ad un endpoint che li deve ricevere ed effettuare l'autenticazione. In particolare questa cosa si articola con l'implementazione di una classe per gestire l'autenticazione, che deve avere i metodi:
- login(username, password) -> bool e mette i cookie
- logout() -> void e cancella i cookie
- is_amministratore() -> bool
- is_docente() -> bool
- is_auth() -> bool

In secondo luogo, ci devono essere gli endpoint:
1. api/login -> prende in input tramite post, (username, password), reindirizza alle dashboard del caso (per il momento fa un semplice echo)
2. api/logout -> prova ad eseguire il logout della classe sopra, in ogni caso reindirizza alla homepage href: ""

**Comment by danesinoo** [comment]
Il logout serve per gestire i cookie lato server e permettere maggiore sicurezza: in questo modo i cookie possono essere cambiati in modo tale che javascript non sia in grado di vederli

**Comment by simocare** [comment]
> Il logout serve per gestire i cookie lato server e permettere maggiore sicurezza: in questo modo i cookie possono essere cambiati in modo tale che javascript non sia in grado di vederli

Non saprei come fare, al massimo mi provi a spiegare mercoledì

**Comment by simocare** [comment]
Capito e fatto.
