### ISSUE TITLE
EditUser

### ISSUE THREAD

**Issue by danesinoo** [Sdraiati/Grigo-Verde#54]
Oltre al fatto che al momento non funziona, un docente non dovrebbe essere in grado di cambiare il proprio ruolo.

**Comment by simocare** [comment]
@danesinoo Cosa non funziona?

**Comment by simocare** [comment]
Per la seconda parte, ho già detto ad @eghosa02 che nella dashboard utente ci dovrebbe essere solo il collegamento alla pagina modifica credenziali, mentre la modifica dell'utente la può fare solo l'amministratore  arrivando dalla pagina lista utenti.

**Comment by danesinoo** [comment]
Dopo che viene cliccato modifica password, il pulsante dovrebbe scomparire
