### ISSUE TITLE
`/spazi`

### ISSUE THREAD

**Issue by rossoc** [Sdraiati/Grigo-Verde#68]
html validar da errore

**Comment by bassupreme** [comment]
Ho individuato i seguenti problemi:
1. nelle breadcrumb vi è un aria-label potenzialmente inutile.
2. l'errore segnalato da html dice che nei nomi degli spazi essenzialmente non ci possano essere dei caratteri di spazio; questo però è un problema dell'html in quanto se vai nel dettaglio spazio il collegamento funziona

**Comment by bassupreme** [comment]
una soluzione possibile è: 
1. vedere se nel nome vi siano degli spazi all'interno del nome dello spazio e in caso mettere il carattere %20 che corrisponde ad uno spazio all'interno di un URL.
